#!/bin/bash

echo "Ticket_booking_app"

echo "mysql root password"

mysql -u root -p -e "create database cinema_db; CREATE USER 'cinema_user'@'localhost' IDENTIFIED BY '1234'; GRANT ALL PRIVILEGES ON cinema_db.* TO cinema_user@localhost; ALTER DATABASE cinema_db CHARACTER SET utf8mb4 COLLATE utf8mb4_polish_ci; "

echo "database created"

mvn clean package

echo "create user ticket_app_user"
sudo useradd ticket_app_user
echo "set password"
sudo passwd ticket_app_user
sudo chown ticket_app_user:ticket_app_user target/ticket_booking_app-0.0.1-SNAPSHOT.jar
sudo chmod 500 target/ticket_booking_app-0.0.1-SNAPSHOT.jar

echo "create service ticket_app"
sudo ln -s $PWD/target/ticket_booking_app-0.0.1-SNAPSHOT.jar  /etc/init.d/ticket_app

echo "start service ticket_app"
sudo service ticket_app start

