#!/bin/bash

res0='curl -s "http://localhost:8080"'
res2='curl -s "http://localhost:8080/screenings?timeBegin=2019-12-04T08:00:00Z&timeEnd=2019-12-04T16:00:00Z"'
res4='curl -s "http://localhost:8080/getSeats?screeningId=2"'
res6='curl -s --header "Content-Type: application/json" \
		--request POST \
 		--data "{ \"name\" : \"Michał\", \"surname\" : \"Janicki\", \"tickets\" : [ { \"screeningId\" : 2, \"seatId\" : 11, \"ticketTypeId\" : 1 },
		{ \"screeningId\" : 2, \"seatId\" : 12, \"ticketTypeId\" : 2 } ]}"\
 		http://localhost:8080/createReservation'
res7='curl -s --request POST \ "http://localhost:8080/confirmReservation?reservationId=1"'


   

echo
eval "$res0"
echo
echo "1. The user selects the day and the time when he/she would like to see the movie."

echo "2. The system lists movies available in the given time interval - title and screening times." 
printf "$res2"
eval "$res2" | jq
echo

echo "3. The user chooses a particular screening."
echo
echo "4. The system gives information regarding screening room and available seats."
printf "$res4"
eval "$res4" | jq
echo
echo "5. The user chooses seats, and gives the name of the person doing the reservation (name and surname)."
echo
echo "6. The system gives back the total amount to pay, reservation expiration time and confirmation link." 
printf "$res6"
eval "$res6" | jq
echo
echo "7. User accesses the link to confirm reservation."
printf "$res7"
echo
eval "$res7" 


